config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'homes#top'
  get 'search' => 'posts#search'


  resources :posts do
    resources :post_images, only: [:new, :create, :destroy, :edit, :update]
    resources :post_comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  get 'posts/new_add'

  resources :users, only: [:index, :show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

def self.search(keyword)
  where(["title like? OR body like?", "%#{keyword}%", "%#{keyword}%"])
end

belongs_to :user

has_many :post_images, dependent: :destroy
accepts_nested_attributes_for :post_images
accepts_attachments_for :post_images, attachment: :image

has_many :post_comments, dependent: :destroy

validates :title, presence: true
validates :body, presence: true

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

belongs_to :user
belongs_to :post

validates :comment, presence: true

end

app/models/post_image.rb
class PostImage < ApplicationRecord

  belongs_to :post
  attachment :image

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :name,{presence: true}
         validates :email,{presence: true, uniqueness: true}

  has_many :posts
  has_many :post_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  attachment :image

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top]

  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
        posts_path
  end

  def after_sign_out_path_for(resource)
        root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :login_check

  def top
  end

  private

  def login_check
    redirect_to posts_path if user_signed_in?
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    post = Post.find(params[:post_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.post_id = post.id
    comment.save
      redirect_to post_path(post)
    #else
      #@error_commemt = comment
      #@post = Post.find(params[:post_id])
      #@post_comment = PostComment.new
      #render 'posts/show'
    #end
  end

  def destroy
    PostComment.find_by(id: params[:id]).destroy
    redirect_to post_path(params[:post_id])
  end



   private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @post_image = PostImage.new
  end

  def create
    @post = Post.find(params[:post_id])
    @post_image = PostImage.new(post_image_params)
    @post_image.post_id = @post.id
    @post_image.save
    redirect_to post_path(@post)
  end

  def edit
    @post = Post.find(params[:post_id])
  end

  def update
    @post = Post.find(params[:post_id])
    @post.user_id = current_user.id
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
  end

  private

  def post_image_params
    params.require(:post_image).permit(:text, :image)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def new
    @post = Post.new
    @posts = Post.all
  end

  def new_add
    @post = Post.find(params[:id])
    @post_new = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def index
    @user = current_user
    @posts = Post.page(params[:page]).reverse_order
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    # @post_images = @post.post_images
    # @post_images = PostImage.where(post_id: @post.id)
    @post_image = PostImage.new
    @post_comment = PostComment.new

  end

  def edit
    @post = Post.find(params[:id])
    @post_images = PostImage.where(post_id: @post.id)
    if @post.user == current_user
      render "edit"
    else
      redirect_to posts_path
    end
  end

  def update
    @post = Post.find(params[:id])
    @post.user_id = current_user.id
    if @post.update(update_post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to users_path
  end

  def search
    @user = current_user
    @posts = Post.search(params[:keyword])
    @keyword = params[:keyword]
    render "index_search"
  end



  private

  def post_params
    params.require(:post).permit(:title, :body, post_images_attributes: [:image, :text])
  end

  def update_post_params
    params.require(:post).permit(:title, :body, post_images_attributes: [:id, :image, :text])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = current_user
    @post = Post.new
    @posts = @user.posts.page(params[:page]).reverse_order
  end

  def show
    @user = User.find(params[:id])
    @post = Post.new
    @posts = @user.posts.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :text, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-11 col-sm-10 col-lg-8 col-xl-6 mx-auto">

      <div class="main-visual">
        <div class="main-visual-content">
          <p class="main-visual-text">
            安心して辿り着けるように。
          </p>
        </div>
      </div>

    <div class="main col-10 mx-auto">
      <div class="row">
        <div class="col text-center">
          <h2>ようこそモクナビ！へ</h2>
        </div>
      </div>
    </div>

    <div class="col-10 mx-auto">
      <div class="row">
        <div class="col text-center">
          <p>登録してルートを検索しよう</p>
          <p><%= link_to "新規登録", new_user_registration_path, class:"btn btn-secondary" %></p>
          <p>アカウントをお持ちの場合はこちら</p>
          <p><%= link_to "ログイン", new_user_session_path, class:"btn btn-secondary" %></p>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mokunavi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <header class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/" >
            <span>モクナビ！</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">

            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <div class="search-form">
                <%= form_with url: search_path, method: :get, local: true do |f| %>
                  <%= f.text_field :keyword, value: @keyword %>
                  <%= f.submit "検索" %>
                <% end %>
              </div>
              <li><%= link_to posts_path, class: "btn btn-link text-light" do %>
               <i class="fas fa-home"></i>ホーム<% end %></li>

               <li><%= link_to users_path, class: "btn btn-link text-light" do %>
               <i class="fas fa-solid fa-user"></i>マイページ<% end %></li>

               <li><%= link_to new_post_path, class: "btn btn-link text-light" do %>
               <i class="fas fa-pen"></i></i>新規投稿<% end %></li>


              <li><%= link_to destroy_user_session_path, method: :delete, class: "btn btn-link text-light" do %>
               <i class="fas fa-sign-out-alt"></i>ログアウト<% end %></li>

               <% else %>

               <li><%= link_to new_user_registration_path, class: "btn btn-link text-light" do %>
               <i class="fas fa-user-plus"></i>新規登録<% end %></li>

               <li><%= link_to new_user_session_path, class: "btn btn-link text-light" do %>
               <i class="fas fa-sign-in-alt"></i>ログイン<% end %></li>
              <% end %>
            </ul>
          </div>

        </div>
      </div>
    </header>
    <%= yield %>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>©︎ 2021 ShokoFurukawa</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/post_images/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2 class="main-title">追加</h2>

      <div class="col-md-8 offset-md-1">
        <h4 class="main-title"><%= @post.title %></h4>
          <div class="post-datetime">
            投稿日時：<%= @post.created_at.strftime('%Y/%m/%d') %>
              <%= link_to "編集", edit_post_path(@post), class: "btn btn-light btn-circle pull-right" %>
              <% if @post.user == current_user %>
              <%= link_to "削除", post_path(@post), method: :delete, class: "btn btn-light btn-circle pull-right" %>
              <% end %>
          <div>

          <div class="mx-auto">
            <p class="post-body"><%= @post.body %></p>
            <% if @post.post_images.present? %>
            <% @post.post_images.each do |post_image| %>
              <%= attachment_image_tag post_image, :image, :fill, 100, 100, format: 'jpeg' %>
              <p><%= post_image.text %></p>
            <% end %>
            <% else %>
              <!--画像はありません-->
            <% end %>
          </div>

          <%= form_with model: @post_image, url:post_post_images_path(@post), local:true do |f| %>
          <div class="form-group">
            <label for="user_image">画像</label><br>
            <%= f.attachment_field :image %>
          </div>
          <div class="form-group">
            <label for="user_image">内容</label><br>
            <%= f.text_area :text %>
          </div>
          <div class="form-group">
            <%= f.submit "追加", class: "btn btn-secondary" %>
          </div>
      </div>
      <% end %>
      
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
     <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

       <h2 class="main-title">投稿編集</h2>

       <%= form_with model: @post, local:true do |f| %>
       <div class="form-group">
         <label for="post-title">タイトル</label><br>
         <%= f.text_field :title %>
       </div>
       <div class="form-group">
         <label for="post_text">本文</label><br>
         <%= f.text_area :body %>
       </div>
       <div class="form-group">
         <label for="post_image"></label><br>
          <%# @post.post_images.each do |post_image| %>
          <%#= f.fields_for :post_images do |post_image| %>

          <%#= post_image.attachment_field :image, placeholder: "画像", class: "form-control-file" %>
          <%#= attachment_image_tag post_image, :image, :fill, 100, 100 %>
          <%= f.fields_for :post_images do |image| %>
            <p><%= attachment_image_tag image.object, :image, :fill, 100, 100 %></p>
            <P><%= image.file_field :image %></P>
            <%= image.hidden_field :id, value: image.object.id %>
            <p><%= image.text_area :text %></p>
        <% end %>
       </div>

        <p><%= f.submit "更新", class: "btn btn-secondary" %></p>
        <% end %>

      </div>
    </div>
</div>

app/views/posts/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <div class-"col-md-3">
      <div class="sidebar_fixed">
        <%= attachment_image_tag @user, :image, :fill, 120, 120, fallback: "no_image.jpg", size: "120x120" %>
        <table class="table">
          <tbody>
            <tr>
              <th>名前</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>プロフィール</th>
              <th><%= @user.text %></th>
            </tr>
            <tr>
              <th colspan="2">
                <%= link_to edit_user_path(@user), class: 'btn btn-outline-secondary btn-block fas' do %>
                <i class="fas fa-user-cog"></i>
                <% end %>
              </th>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <div class="col-md-8 offset-md-1">
        <h2 class="main-title">みんなの投稿</h2>
        <table>
            <% @posts.each do |post| %>
            <tr>
              <td>
                <%= link_to user_path(post.user) do %>
                <%= attachment_image_tag post.user, :image, :fill, 60, 60, fallback: "no_image.jpg", size: "60x60" %>
                <% end %>
              </td>
              <td><%= link_to post.title, post_path(post.id) %></td>
              <td><%#= link_to "コメント#{post.post_comments.count}件", post_path(post.id) %></td>
            </tr>
          <% end %>
        </table>
        <p class="pagenate"><%= paginate @posts %></p>
    </div>
  </div>
</div>

app/views/posts/index_search.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class-"col-md-3">

      <div class="sidebar_fixed">
        <%= attachment_image_tag @user, :image, :fill, 120, 120, fallback: "no_image.jpg", size: "120x120" %>
        <table class="table">
          <tbody>
            <tr>
              <th>名前</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>プロフィール</th>
              <th><%= @user.text %></th>
            </tr>
            <tr>
              <th colspan="2">
                <%= link_to edit_user_path(@user), class: 'btn btn-outline-secondary btn-block fas' do %>
                <i class="fas fa-user-cog"></i>
                <% end %>
              </th>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <div class="col-md-8 offset-md-1">
        <h2 class="main-title">検索一覧</h2>
        <table>
          <thead>
            <th></th>
          </thead>
          <tbody>
            <% @posts.each do |post| %>
            <tr>
              <td>
                <%= link_to post_path(post.id) do %>
                <%= attachment_image_tag post.user, :image, :fill, 60, 60, fallback: "no_image.jpg", size: "60x60" %>
                <% end %>
              </td>
              <td><%= link_to post.title, post_path(post.id) %></td>
              <td><%= link_to "コメント#{post.post_comments.count}件", post_path(post.id) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2 class="main-title">新規投稿</h2>

      <% if @post.errors.any? %>
        <%= @post.errors.count %>件のエラーが発生しました
        <% @post.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>

        <%= form_with model: @post, url:posts_path, local:true do |f| %>
        <div class="form-group">
          <label for="post-title">タイトル</label><br>
          <%= f.text_field :title, autofocus: true %>
        </div>
        <div class="form-group">
          <label for="post-text">内容</label><br>
          <%= f.text_area :body %>
        </div>
        <div class="form-group">
          <%= f.submit "投稿", class: "btn btn-secondary" %>
        </div>
        <% end %>

      </div>
    </div>
</div>

app/views/posts/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class-"col-md-3">

      <div class="sidebar_fixed">
        <%= attachment_image_tag @user, :image, :fill, 120, 120, fallback: "no_image.jpg", size: "120x120" %>
        <table class="table">
          <tbody>
            <tr>
              <th>名前</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>プロフィール</th>
              <th><%= @user.text %></th>
            </tr>
            <tr>
              <th colspan="2">
                <%= link_to edit_user_path(@user), class: 'btn btn-outline-secondary btn-block fas' do %>
                <i class="fas fa-user-cog"></i>
                <% end %>
              </th>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2 class="main-title"><%= @post.title %></h2>
      <div class="post-datetime">
        投稿日時：<%= @post.created_at.strftime('%Y/%m/%d') %>
        <% if @post.user == current_user %>
        <%= link_to "編集", edit_post_path(@post), class: "btn btn-light btn-circle pull-right" %>
        <% end %>

        <% if @post.user == current_user %>
        <%= link_to "削除", post_path(@post), method: :delete, class: "btn btn-light btn-circle pull-right" %>
        <% end %>

        <% if @post.user == current_user %>
        <%= link_to "追加", new_post_post_image_path(@post), class: "btn btn-light btn-circle pull-right" %>
        <% end %>
      </div>



      <div class="mx-auto">
        <p class="post-body"><%= @post.body %></p>
        <% @post.post_images.each do |post_image| %>
          <%= attachment_image_tag post_image, :image, :fill, 200, 200, format: 'jpeg' %>
          <p class="post-text"><%= post_image.text %></p>
        <% end %>
      </div>

      <div>
        <p class="post-comments">コメント件数：<%= @post.post_comments.count %></p>
          <% @post.post_comments.each do |post_comment| %>
            <p>
              <%= post_comment.user.name %>：
              <%= post_comment.comment %><br>
              <%= post_comment.created_at.strftime('%Y/%m/%d') %>
              <% if post_comment.user == current_user %>
              <%= link_to "削除", post_post_comment_path(post_comment.post, post_comment), method: :delete %>
              <% end %>
            </p>
          <% end %>
      </div>

      <% if @error_comment.present? %>
        <div id="error_explanation">
          <h2><%= @error_comment.errors.count %>件のエラーが発生しました。</h2>
          <ul>
            <% @error_comment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="post-form">
        <%= form_with(model:[@post, @post_comment], local: true) do |f| %>
          <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
          <%= f.submit "送信する" %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

          <h2 class="main-title">プロフィール編集</h2>

          <!--エラー通知-->
          <% if @user.errors.any? %>
          <%= @user.errors.count %> errors prohibited this obj from being saved:
            <% @user.errors.full_messages.each do |message| %>
              <%= message %>
            <% end %>
          <% end %>


          <%= form_with model: @user, url:user_path, local:true do |f| %>
          <div class="form-group">
            <label for="user_image">プロフィール画像</label><br>
            <%= f.attachment_field :image %>
          </div>
          <div class="form-group">
            <label for="user_name">名前</label><br>
            <%= f.text_field :name %>
          </div>
          <div class="form-group">
            <label for="user_text">紹介文</label><br>
            <%= f.text_area :text %>
          </div>
          <div class="form-group">
            <%= f.submit "更新", class: "btn btn-secondary" %>
          </div>
          <% end %>

        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class-"col-md-3">

      <div class="sidebar_fixed">
        <%= attachment_image_tag @user, :image, :fill, 120, 120, fallback: "no_image.jpg", size: "120x120" %>
        <table class="table">
          <tbody>
            <tr>
              <th>名前</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>プロフィール</th>
              <th><%= @user.text %></th>
            </tr>
            <tr>
              <th colspan="2">
                <%= link_to edit_user_path(@user), class: 'btn btn-outline-secondary btn-block fas' do %>
                <i class="fas fa-user-cog"></i>
                <% end %>
              </th>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <div class="col-md-8 offset-md-1">
        <h2 class="main-title"><%= @user.name %>の投稿</h2>

        <table>
          <thead>
            <th></th>
          </thead>
          <tbody>
            <% @posts.each do |post| %>
            <tr>
              <td>
                <%= link_to user_path(post.user) do %>
                <%= attachment_image_tag post.user, :image, :fill, 60, 60, fallback: "no_image.jpg", size: "60x60" %>
                <% end %>
              </td>
              <td><%= link_to post.title, post_path(post.id) %></td>
              <td><%#= link_to "コメント#{post.post_comments.count}件", post_path(post.id) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <p class="pagenate"><%= paginate @posts %></p>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class-"col-md-3">

      <div class="sidebar_fixed">
        <%= attachment_image_tag @user, :image, :fill, 120, 120, fallback: "no_image.jpg", size: "120x120" %>
        <table class="table">
          <tbody>
            <tr>
              <th>名前</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>プロフィール</th>
              <th><%= @user.text %></th>
            </tr>
            <tr>
              <th colspan="2">
                <%= link_to edit_user_path(@user), class: 'btn btn-outline-secondary btn-block fas' do %>
                <i class="fas fa-user-cog"></i>
                <% end %>
              </th>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <div class="col-md-8 offset-md-1">
        <h2 class="main-title"><%= @user.name %>の投稿</h2>

        <table>
          <thead>
            <th></th>
          </thead>
          <tbody>
            <% @posts.each do |post| %>
          </tbody>
            <tr>
              <td>
                <%= link_to users_path(post.user) do %>
                <%= attachment_image_tag post.user, :image, :fill, 60, 60, fallback: "no_image.jpg", size: "60x60" %>
                <% end %>
              </td>
              <td><%= link_to post.title, post_path(post.id) %></td>
              <td><%#= link_to "コメント#{post.post_comments.count}件", post_path(post.id) %></td>
            </tr>
          <% end %>
        </table>
        <p class="pagenate"><%= paginate @posts %></p>
    </div>
  </div>
</div>